# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SOLANAui2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SOLANA(object):
    def setupUi(self, SOLANA):
        SOLANA.setObjectName("SOLANA")
        SOLANA.setEnabled(True)
        SOLANA.resize(556, 456)
        self.label = QtWidgets.QLabel(SOLANA)
        self.label.setGeometry(QtCore.QRect(-10, -10, 571, 471))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/Mafia/OneDrive/Documents/projects/AI/hackathon project/NANOTECH.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(SOLANA)
        self.pushButton.setGeometry(QtCore.QRect(460, 400, 75, 41))
        font = QtGui.QFont()
        font.setFamily("Constantia")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color:transparent;\n"
"color: rgb(12, 201, 204);")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(SOLANA)
        QtCore.QMetaObject.connectSlotsByName(SOLANA)

    def retranslateUi(self, SOLANA):
        _translate = QtCore.QCoreApplication.translate
        SOLANA.setWindowTitle(_translate("SOLANA", "SOLANA"))
        self.pushButton.setText(_translate("SOLANA", "START"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SOLANA = QtWidgets.QDialog()
    ui = Ui_SOLANA()
    ui.setupUi(SOLANA)
    SOLANA.show()
    sys.exit(app.exec_())
